global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'spring boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9797']
